# Form implementation generated from reading ui file '.\login.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 600)
        MainWindow.setMinimumSize(QtCore.QSize(850, 600))
        MainWindow.setMaximumSize(QtCore.QSize(850, 600))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_contenedor = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_contenedor.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_contenedor.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_contenedor.setObjectName("frame_contenedor")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_contenedor)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_contenedor)
        self.frame_4.setMinimumSize(QtCore.QSize(300, 201))
        self.frame_4.setMaximumSize(QtCore.QSize(320, 16777215))
        self.frame_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_4.setMinimumSize(QtCore.QSize(0, 0))
        self.label_4.setMaximumSize(QtCore.QSize(320, 350))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(".\\Images/Logo.jpeg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame = QtWidgets.QFrame(parent=self.frame_contenedor)
        self.frame.setStyleSheet("\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 222, 255, 255), stop:0.903955 rgba(0, 107, 255, 255));")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(parent=self.frame)
        self.label_5.setStyleSheet("font: 700 italic 16pt \"Verdana\";\n"
"background-color: None\n"
"")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(0, 0, -1, 0)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_3.setStyleSheet("background-color: None;\n"
"font: 700 italic 16pt \"Verdana\";\n"
"color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 2, 1, 6)
        self.label_6 = QtWidgets.QLabel(parent=self.frame)
        self.label_6.setStyleSheet("background-color: None;\n"
"font: 700 italic 12pt \"Verdana\";")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 11, 2, 1, 5)
        spacerItem = QtWidgets.QSpacerItem(100, 25, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout.addItem(spacerItem, 2, 2, 1, 6)
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setStyleSheet("background-color: None;\n"
"font: 700 italic 11pt \"Verdana\";")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 2, 2, 4)
        spacerItem1 = QtWidgets.QSpacerItem(100, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout.addItem(spacerItem1, 4, 2, 1, 6)
        self.txt_Usuario = QtWidgets.QLineEdit(parent=self.frame)
        self.txt_Usuario.setMinimumSize(QtCore.QSize(160, 30))
        self.txt_Usuario.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.txt_Usuario.setStyleSheet("QLineEdit {\n"
"                background-color: rgb(255, 255, 255);\n"
"                 border-radius:9px;\n"
"                padding: 5px;\n"
"                 border: 1px solid rgb(255, 255, 255);\n"
"            }\n"
"            QLineEdit:hover {\n"
"                \n"
"    border-color: rgb(170, 170, 255);\n"
"            }")
        self.txt_Usuario.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.txt_Usuario.setObjectName("txt_Usuario")
        self.gridLayout.addWidget(self.txt_Usuario, 3, 6, 1, 2)
        self.txt_Contrasenia = QtWidgets.QLineEdit(parent=self.frame)
        self.txt_Contrasenia.setMinimumSize(QtCore.QSize(160, 30))
        self.txt_Contrasenia.setStyleSheet("QLineEdit {\n"
"                background-color: rgb(255, 255, 255);\n"
"                 border-radius:9px;\n"
"                padding: 5px;\n"
"                 border: 1px solid rgb(255, 255, 255);\n"
"            }\n"
"            QLineEdit:hover {\n"
"                \n"
"    border-color: rgb(170, 170, 255);\n"
"            }")
        self.txt_Contrasenia.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txt_Contrasenia.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.txt_Contrasenia.setObjectName("txt_Contrasenia")
        self.gridLayout.addWidget(self.txt_Contrasenia, 5, 6, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout.addItem(spacerItem2, 7, 2, 2, 6)
        spacerItem3 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem3, 10, 2, 1, 6)
        spacerItem4 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        self.gridLayout.addItem(spacerItem4, 0, 2, 1, 6)
        self.label_7 = QtWidgets.QLabel(parent=self.frame)
        self.label_7.setStyleSheet("background-color: None;\n"
"font: 700 italic 12pt \"Verdana\";")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 11, 7, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setStyleSheet("background-color: None;\n"
"font: 700 italic 11pt \"Verdana\";")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 2, 1, 4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem5, 9, 7, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem6, 9, 2, 1, 1)
        self.btn_Salir = QtWidgets.QPushButton(parent=self.frame)
        self.btn_Salir.setMinimumSize(QtCore.QSize(130, 30))
        self.btn_Salir.setMaximumSize(QtCore.QSize(160, 40))
        self.btn_Salir.setStyleSheet("QPushButton{\n"
"font: 700 italic 10pt \"Verdana\";\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(19, 203, 149, 255), stop:1 rgba(17, 204, 149, 255));\n"
"border-radius:9px;\n"
"}\n"
"QPushButton:hover{\n"
"font: 700 italic 10pt \"Verdana\";\n"
"    background-color: #00def6;\n"
"border-radius:9px;\n"
"}")
        self.btn_Salir.setObjectName("btn_Salir")
        self.gridLayout.addWidget(self.btn_Salir, 9, 6, 1, 1)
        self.btn_Ingresar = QtWidgets.QPushButton(parent=self.frame)
        self.btn_Ingresar.setMinimumSize(QtCore.QSize(130, 30))
        self.btn_Ingresar.setStyleSheet("QPushButton{\n"
"font: 700 italic 10pt \"Verdana\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(19, 203, 149, 255), stop:1 rgba(17, 204, 149, 255));\n"
"border-radius:9px;\n"
"}\n"
"QPushButton:hover{\n"
"font: 700 italic 10pt \"Verdana\";\n"
"    background-color: #00def6;\n"
"border-radius:9px;\n"
"}")
        self.btn_Ingresar.setObjectName("btn_Ingresar")
        self.gridLayout.addWidget(self.btn_Ingresar, 9, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout_2.addWidget(self.frame_contenedor)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.btn_Salir.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "Control de Asistencia IA"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Bienvenido</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "by:"))
        self.label_2.setText(_translate("MainWindow", "Contraseña:"))
        self.txt_Usuario.setPlaceholderText(_translate("MainWindow", "Usuario"))
        self.txt_Contrasenia.setPlaceholderText(_translate("MainWindow", "Contraseña"))
        self.label_7.setText(_translate("MainWindow", "Suport:"))
        self.label.setText(_translate("MainWindow", "Usuario:"))
        self.btn_Salir.setText(_translate("MainWindow", "Salir"))
        self.btn_Ingresar.setText(_translate("MainWindow", "Ingresar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
