# Form implementation generated from reading ui file '.\Loguin.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
#from PyQt6.QtGui import QPixmap

class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(1122, 723)
        login.setMinimumSize(QtCore.QSize(1122, 723))
        login.setMaximumSize(QtCore.QSize(1122, 723))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/OpenCV.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        login.setWindowIcon(icon)
        login.setWindowOpacity(10000.0)
        login.setStyleSheet("background-color: rgba(170, 220, 205,200);\n"
"padding:0px;")
        self.verticalLayout = QtWidgets.QVBoxLayout(login)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=login)
        self.frame.setEnabled(True)
        self.frame.setMinimumSize(QtCore.QSize(0, 130))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 130))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 130))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 130))
        self.frame_2.setStyleSheet("background-color: rgb(44, 91, 116);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_6.setMinimumSize(QtCore.QSize(100, 80))
        self.label_6.setMaximumSize(QtCore.QSize(200, 80))
        self.label_6.setStyleSheet("padding-left:100px;")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("images/iniciar-sesion.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.label_5 = QtWidgets.QLabel(parent=self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(40)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left:10px;")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(parent=login)
        self.frame_3.setStyleSheet("background-color:rgb(0, 0, 0);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_4.setMaximumSize(QtCore.QSize(460, 16777215))
        self.frame_4.setStyleSheet("#frame_4{\n"
"  border-image:url(images/fondo-l.jpg);\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_16 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_16.setStyleSheet("background-color:rgba(200,200,200,110);\n"
"border-radius: 15px;\n"
"padding-top:125px;\n"
"padding-bottom:125px;")
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("images/sistemas 4.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_2.addWidget(self.label_16)
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_5.setStyleSheet("#frame_5{\n"
"  border-image:url(images/fondo-r.jpg);\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_12 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_12.setGeometry(QtCore.QRect(80, 110, 511, 361))
        self.label_12.setStyleSheet("#label_12{\n"
"  background-color:rgba(0,0,0,110);\n"
"  border-radius: 15px;\n"
"}")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_13.setGeometry(QtCore.QRect(230, 130, 261, 40))
        font = QtGui.QFont("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color:rgba(255,255,255,210);")
        self.label_13.setObjectName("label_13")
        self.in_User = QtWidgets.QLineEdit(parent=self.frame_5)
        self.in_User.setGeometry(QtCore.QRect(310, 200, 241, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.in_User.setFont(font)
        self.in_User.setStyleSheet("background-color:rgba(0,0,0,100);\n"
"border-radius:10px;\n"
"border:none;\n"
"border-bottom:2px solid rgba(255,250,252,255);\n"
"color: rgba(255,255,255,230);\n"
"padding-bottom:1px;")
        self.in_User.setObjectName("in_User")
        self.in_Password = QtWidgets.QLineEdit(parent=self.frame_5)
        self.in_Password.setGeometry(QtCore.QRect(310, 280, 241, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.in_Password.setFont(font)
        self.in_Password.setStyleSheet("background-color:rgba(0,0,0,100);\n"
"border-radius:10px;\n"
"border:none;\n"
"border-bottom:2px solid rgba(255,250,252,255);\n"
"color: rgba(255,255,255,230);\n"
"padding-bottom:2px;")
        self.in_Password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.in_Password.setObjectName("in_Password")
        self.label_14 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_14.setGeometry(QtCore.QRect(190, 206, 121, 31))
        self.label_14.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color:rgba(255,255,255,210);\n"
"\n"
"font: 75 12pt \"Consolas\";\n"
"")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_15.setGeometry(QtCore.QRect(180, 287, 121, 31))
        self.label_15.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color:rgba(255,255,255,210);\n"
"\n"
"font: 75 12pt \"Consolas\";\n"
"")
        self.label_15.setObjectName("label_15")
        self.btn_Salir = QtWidgets.QPushButton(parent=self.frame_5)
        self.btn_Salir.setEnabled(True)
        self.btn_Salir.setGeometry(QtCore.QRect(240, 370, 111, 40))
        self.btn_Salir.setMinimumSize(QtCore.QSize(50, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.btn_Salir.setFont(font)
        self.btn_Salir.setStyleSheet("QPushButton#btn_Salir{    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.418719 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton#btn_Salir:hover{    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.418719 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"\n"
"QPushButton#btn_Salir:pressed{    \n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(48,132,132,200);\n"
"}\n"
"")
        self.btn_Salir.setObjectName("btn_Salir")
        self.btn_Login = QtWidgets.QPushButton(parent=self.frame_5)
        self.btn_Login.setEnabled(True)
        self.btn_Login.setGeometry(QtCore.QRect(390, 370, 111, 40))
        self.btn_Login.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.btn_Login.setFont(font)
        self.btn_Login.setStyleSheet("QPushButton#btn_Login{    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.418719 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton#btn_Login:hover{    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.418719 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"\n"
"QPushButton#btn_Login:pressed{    \n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(48,132,132,200);\n"
"}")
        self.btn_Login.setObjectName("btn_Login")
        self.label = QtWidgets.QLabel(parent=self.frame_5)
        self.label.setGeometry(QtCore.QRect(70, 540, 251, 21))
        self.label.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color:rgba(255,255,255,210);\n"
"\n"
"font: 75 10pt \"Consolas\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_2.setGeometry(QtCore.QRect(130, 206, 41, 31))
        self.label_2.setMinimumSize(QtCore.QSize(41, 31))
        self.label_2.setMaximumSize(QtCore.QSize(41, 31))
        self.label_2.setStyleSheet("background-color:rgba(200,200,200,100);\n"
"color:rgba(255,255,255,210);\n"
"border-radius:12px;")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("images/usuario.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_3.setGeometry(QtCore.QRect(130, 290, 41, 31))
        self.label_3.setMinimumSize(QtCore.QSize(41, 31))
        self.label_3.setMaximumSize(QtCore.QSize(41, 31))
        self.label_3.setStyleSheet("background-color:rgba(200,200,200,100);\n"
"color:rgba(255,255,255,210);\n"
"border-radius:12px;")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("images/contrasena.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.frame_5)
        self.verticalLayout.addWidget(self.frame_3)

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "inicio session"))
        self.label_5.setText(_translate("login", "Control de Asistencia.AI"))
        self.label_13.setText(_translate("login", "Inicio Session"))
        self.in_User.setPlaceholderText(_translate("login", "User name"))
        self.in_Password.setPlaceholderText(_translate("login", "Password"))
        self.label_14.setText(_translate("login", "usuario: "))
        self.label_15.setText(_translate("login", "contraseña:"))
        self.btn_Salir.setText(_translate("login", "S a l i r"))
        self.btn_Login.setText(_translate("login", "l o g  I n"))
        self.label.setText(_translate("login", "by:........................."))

"""
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login = QtWidgets.QWidget()
    ui = Ui_login()
    ui.setupUi(login)
    login.show()
    sys.exit(app.exec())"""
